### ISSUE TITLE
Plugin now broken w/ test data

### ISSUE THREAD

**Issue by patpicos** [prombouts/vsts-auto-tagging#7]
Peterrrrr 

I reran the pipeline w/ the tagging.
Looks like you have test code in place...

```
2018-10-18T13:05:12.2133046Z ##[section]Starting: RG and Resources Tags
2018-10-18T13:05:12.2137429Z ==============================================================================
2018-10-18T13:05:12.2137923Z Task         : Auto Tag Resources in Resource Group
2018-10-18T13:05:12.2138315Z Description  : Automatically add tags to all resources within a resource group
2018-10-18T13:05:12.2138483Z Version      : 1.0.39
2018-10-18T13:05:12.2138596Z Author       : Peter Rombouts
2018-10-18T13:05:12.2138770Z Help         : Automatically add tags to all resources within a resource group
2018-10-18T13:05:12.2138919Z ==============================================================================
2018-10-18T13:05:13.1070271Z Entering script tagginggroup.ps1
2018-10-18T13:05:13.3130461Z ##[command]Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\AzureRM\2.1.0\AzureRM.psd1 -Global
2018-10-18T13:05:17.1853983Z ##[warning]The names of some imported commands from the module 'AzureRM.Websites' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
2018-10-18T13:05:17.1919280Z ##[warning]The names of some imported commands from the module 'AzureRM' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
2018-10-18T13:05:17.2488846Z ##[command]Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\AzureRM.profile\2.1.0\AzureRM.profile.psd1 -Global
2018-10-18T13:05:17.3078955Z ##[command]Add-AzureRMAccount -ServicePrincipal -Tenant *** -Credential System.Management.Automation.PSCredential -EnvironmentName AzureCloud
2018-10-18T13:05:17.9562644Z ##[command]Select-AzureRMSubscription -SubscriptionId 1*************c7 -TenantId ***
2018-10-18T13:05:18.1392653Z ResourceGroupName= rg-jordin-data
2018-10-18T13:05:18.1394473Z Tags= Hello,World
2018-10-18T13:05:18.1394644Z TestPair,TestValue
2018-10-18T13:05:18.1408803Z tagResourceGroup= 
2018-10-18T13:05:21.3130469Z ##[error]1:05:21 PM - Provided resource group does not exist.
2018-10-18T13:05:21.3526939Z ##[section]Finishing: RG and Resources Tags

```

**Comment by prombouts** [comment]
Yes this is fixed in 1.0.40.the 39 version was a wrong commit into github...

**Comment by prombouts** [comment]
You should see the version 1.0.40 if you run your pipeline again. 1.0.39 was online for a couple of minutes...

**Comment by patpicos** [comment]
Just ran and it still had 1.0.39
```
2018-10-18T15:44:54.0000685Z ##[section]Starting: RG and Resources Tags
2018-10-18T15:44:54.0004382Z ==============================================================================
2018-10-18T15:44:54.0004490Z Task         : Auto Tag Resources in Resource Group
2018-10-18T15:44:54.0004569Z Description  : Automatically add tags to all resources within a resource group
2018-10-18T15:44:54.0004626Z Version      : 1.0.39
2018-10-18T15:44:54.0004693Z Author       : Peter Rombouts
2018-10-18T15:44:54.0004754Z Help         : Automatically add tags to all resources within a resource group
2018-10-18T15:44:54.0004838Z ==============================================================================
2018-10-18T15:44:54.9366888Z Entering script tagginggroup.ps1
2018-10-18T15:44:55.1506116Z ##[command]Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\AzureRM\2.1.0\AzureRM.psd1 -Global
2018-10-18T15:44:59.0684153Z ##[warning]The names of some imported commands from the module 'AzureRM.Websites' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
2018-10-18T15:44:59.0749418Z ##[warning]The names of some imported commands from the module 'AzureRM' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
2018-10-18T15:44:59.1337445Z ##[command]Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\AzureRM.profile\2.1.0\AzureRM.profile.psd1 -Global
2018-10-18T15:44:59.1885565Z ##[command]Add-AzureRMAccount -ServicePrincipal -Tenant *** -Credential System.Management.Automation.PSCredential -EnvironmentName AzureCloud
2018-10-18T15:44:59.8250830Z ##[command]Select-AzureRMSubscription -SubscriptionId 1824bc1e-b99a-4dab-9a84-b0d5f05f83c7 -TenantId ***
2018-10-18T15:44:59.9041226Z ResourceGroupName= rg-jordin-data
2018-10-18T15:44:59.9042997Z Tags= Hello,World
2018-10-18T15:44:59.9043216Z TestPair,TestValue
2018-10-18T15:44:59.9056188Z tagResourceGroup= 
2018-10-18T15:45:04.5391638Z ##[error]3:45:04 PM - Provided resource group does not exist.
2018-10-18T15:45:04.5825969Z ##[section]Finishing: RG and Resources Tags

```

**Comment by prombouts** [comment]
Marketplace holds 1.0.40. Sometimes removing and readding it to the pipeline helps. https://marketplace.visualstudio.com/items?itemName=PeterRombouts.autotagging-extension

**Comment by patpicos** [comment]
that is weird. I deleted and added the tag, re-ran and it is still showing 1.0.39

ran at 1:35PM EDT

```
2018-10-18T17:35:40.5712005Z ##[section]Starting: RG and Resources Tags
2018-10-18T17:35:40.5716474Z ==============================================================================
2018-10-18T17:35:40.5716612Z Task         : Auto Tag Resources in Resource Group
2018-10-18T17:35:40.5716691Z Description  : Automatically add tags to all resources within a resource group
2018-10-18T17:35:40.5716779Z Version      : 1.0.39
2018-10-18T17:35:40.5716845Z Author       : Peter Rombouts
2018-10-18T17:35:40.5716938Z Help         : Automatically add tags to all resources within a resource group
2018-10-18T17:35:40.5717024Z ==============================================================================
2018-10-18T17:35:41.4837933Z Entering script tagginggroup.ps1
2018-10-18T17:35:41.6878801Z ##[command]Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\AzureRM\2.1.0\AzureRM.psd1 -Global
2018-10-18T17:35:45.5203813Z ##[warning]The names of some imported commands from the module 'AzureRM.Websites' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
2018-10-18T17:35:45.5251498Z ##[warning]The names of some imported commands from the module 'AzureRM' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
2018-10-18T17:35:45.5977430Z ##[command]Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\AzureRM.profile\2.1.0\AzureRM.profile.psd1 -Global
2018-10-18T17:35:45.6526782Z ##[command]Add-AzureRMAccount -ServicePrincipal -Tenant *** -Credential System.Management.Automation.PSCredential -EnvironmentName AzureCloud
2018-10-18T17:35:46.3284059Z ##[command]Select-AzureRMSubscription -SubscriptionId 18************** -TenantId ***
2018-10-18T17:35:46.5092213Z ResourceGroupName= rg-jordin-data
2018-10-18T17:35:46.5094961Z Tags= Hello,World
2018-10-18T17:35:46.5095153Z TestPair,TestValue
2018-10-18T17:35:46.5107516Z tagResourceGroup= 
2018-10-18T17:35:51.0894363Z ##[error]5:35:51 PM - Provided resource group does not exist.
2018-10-18T17:35:51.1325920Z ##[section]Finishing: RG and Resources Tags
```

**Comment by prombouts** [comment]
Could you remove the step, save the pipeline and refresh your browser? Then add it again? Sometimes vsts caches pretty hard.

**Comment by patpicos** [comment]
cleared cache in browser, restarted browser....still going w/ .39 :(

that is so weird. Any chance to repush another version?

**Comment by prombouts** [comment]
Just version bumped to 41: https://marketplace.visualstudio.com/items?itemName=PeterRombouts.autotagging-extension

Tested with Hosted 2017 agent:
2018-10-18T18:55:38.5503502Z ##[section]Starting: AutoTagger
2018-10-18T18:55:38.5508119Z ==============================================================================
2018-10-18T18:55:38.5508209Z Task         : Auto Tag Resources in Resource Group
2018-10-18T18:55:38.5508283Z Description  : Automatically add tags to all resources within a resource group
2018-10-18T18:55:38.5508339Z Version      : 1.0.41
2018-10-18T18:55:38.5508392Z Author       : Peter Rombouts
2018-10-18T18:55:38.5508466Z Help         : Automatically add tags to all resources within a resource group
2018-10-18T18:55:38.5508528Z ==============================================================================

I hope it is fixed now on your end also,

**Comment by patpicos** [comment]
Adding the logs for the follow up run post adding 1 tag manually:

```
2018-10-18T20:21:21.5976798Z Writing 6 tags to resource /subscriptions/***************/resourceGroups/azu-eus2-dev-rg-DPmetastore/providers/Microsoft.Sql/servers/azu-eus2-dev-sqldb-metastore/databases/metastore...
2018-10-18T20:21:25.5540894Z Name              : metastore
2018-10-18T20:21:25.5594998Z ResourceId        : /subscriptions/***************/resourceGroups/azu-eus2-dev-rg-DPmetastore/prov
2018-10-18T20:21:25.5595590Z                     iders/Microsoft.Sql/servers/azu-eus2-dev-sqldb-metastore/databases/metastore
2018-10-18T20:21:25.5596523Z ResourceName      : azu-eus2-dev-sqldb-metastore/metastore
2018-10-18T20:21:25.5596968Z ResourceType      : Microsoft.Sql/servers/databases
2018-10-18T20:21:25.5598050Z Kind              : v12.0,user
2018-10-18T20:21:25.5599312Z ResourceGroupName : azu-eus2-dev-rg-DPmetastore
2018-10-18T20:21:25.5600072Z Location          : East US 2
2018-10-18T20:21:25.5601146Z SubscriptionId    : ***************
2018-10-18T20:21:25.5601764Z Tags              : {Application, repositoryUrl, Description, CostCenter...}
2018-10-18T20:21:25.5609977Z Properties        : @{databaseId=***********; edition=Standard; status=Online; 
2018-10-18T20:21:25.5610319Z                     serviceLevelObjective=S0; collation=SQL_Latin1_General_CP1_CI_AS; maxSizeBytes=268435456000; 
2018-10-18T20:21:25.5610630Z                     creationDate=2018-10-12T16:11:33.587Z; 
2018-10-18T20:21:25.5611200Z                     currentServiceObjectiveId=f1173c43-91bd-4aaa-973c-54e79e15235b; 
2018-10-18T20:21:25.5611661Z                     requestedServiceObjectiveId=f1173c43-91bd-4aaa-973c-54e79e15235b; 
2018-10-18T20:21:25.5612752Z                     requestedServiceObjectiveName=S0; sampleName=; defaultSecondaryLocation=Central US; 
2018-10-18T20:21:25.5613076Z                     earliestRestoreDate=2018-10-12T16:12:07.647Z; elasticPoolName=; containmentState=2; 
2018-10-18T20:21:25.5613394Z                     readScale=Disabled; failoverGroupId=; zoneRedundant=False; isUpgradeRequested=False}
```
